version: "3.8"

services:
  app:
    build: .
    container_name: bot-server
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env.production

  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
