from openai import OpenAI
from utils.logger import *

gpt_client = OpenAI()


def add_response_to_thread(thread_id: str, message: str) -> None:
    gpt_client.beta.threads.messages.create(
        thread_id=thread_id,
        role="user",
        content=message,
    )


def get_chatgpt_response(thread_id: str, assistant_id: str) -> str:
    run = gpt_client.beta.threads.runs.create(
        thread_id=thread_id, assistant_id=assistant_id
    )

    while True:
        run_status = gpt_client.beta.threads.runs.retrieve(
            thread_id=thread_id, run_id=run.id
        )

        if run_status.status == "completed":
            logger.info("Run status complete - Generated reply!")
            messages = gpt_client.beta.threads.messages.list(thread_id=thread_id)
            return messages.data[0].content[0].text.value
        elif run_status.status == "failed":
            logger.error("Run execution failed - Reply couldn't be generated by model")
            raise Exception("[Openai] Failed to generate response")
